import type { BasketSummary } from './basket-data'

// ─────────────────────────────────────────────────────────────────────────────
// SHORT LINKS (owner 2026-08-01: "condense all urls down… don't break existing
// basket urls / existing creators, just new baskets, bundles, creators going
// forward").
//
//   /token?addr=0x2937…8088&chain=4663   62 chars   →   /t/r/T2       8 chars
//   /creator/0xf4e6…6554                 51 chars   →   /c/colby.eth
//   /bundle/0xf4e6…6554/1a2b3c4d         60 chars   →   /b/0xf4e6…/1a2b3c4d
//
// THE RULE THAT MATTERS IS STABILITY. Every long URL keeps working forever,
// unchanged — they are shared on X and in Telegram and we do not get to expire
// them. This is additive routing, never a rename: the old routes still resolve,
// and the only thing that changes is which form the app MINTS from now on.
//
// A symbol alone is not a safe permanent id: two baskets on one chain can carry
// the same ticker, and a link minted while a symbol was unique would silently
// become ambiguous the day someone launches a twin. So the canonical short ref
// is `SYMBOL-<8 hex>` — the symbol for humans, the address prefix for the
// machine — and it can never change meaning. A BARE symbol is still accepted as
// a convenience (people will type it), and when that turns out to be ambiguous
// the resolver says so instead of guessing which basket you meant.
//
// Chain letters keep the path short while staying operator-generic: a chain the
// kit doesn't have a letter for simply uses its numeric id, so a self-hosted
// deployment on any chain gets working short links without editing this file.
// ─────────────────────────────────────────────────────────────────────────────

const CHAIN_LETTER: Record<number, string> = { 1: 'e', 8453: 'b', 4663: 'r' }
const LETTER_CHAIN: Record<string, number> = { e: 1, b: 8453, r: 4663 }

/** Path segment for a chain — a letter where we have one, else the raw id. */
export function chainSlug(chainId: number): string {
  return CHAIN_LETTER[chainId] ?? String(chainId)
}

/** Inverse of `chainSlug`. Returns null for a segment that is neither. */
export function chainFromSlug(slug: string): number | null {
  // Own-property only: `constructor` and `__proto__` are already lowercase and
  // would otherwise come back as Object.prototype members typed `number`.
  const letter = Object.prototype.hasOwnProperty.call(LETTER_CHAIN, slug.toLowerCase())
    ? LETTER_CHAIN[slug.toLowerCase()]
    : undefined
  if (letter) return letter
  // Digits only — a bare Number() also accepts 0x10, 1e3, 0b11 and ' 1', giving
  // one chain many spellings and undercutting the point of a canonical link.
  if (!/^[0-9]+$/.test(slug)) return null
  const n = Number(slug)
  return Number.isInteger(n) && n > 0 ? n : null
}

/** The 8-hex machine half of a ref — enough to be unique among any realistic
 *  number of baskets, and unlike a symbol it cannot be taken by someone else. */
export const addrPrefix = (address: string): string => address.toLowerCase().slice(2, 10)

const SAFE_SYMBOL = /^[A-Za-z0-9]{1,11}$/

/** The canonical short ref for a basket: `SYMBOL-<8hex>`, or just the address
 *  prefix when the symbol has characters that don't belong in a path. */
export function basketRef(b: { symbol: string; address: string }): string {
  const sym = (b.symbol ?? '').trim()
  return SAFE_SYMBOL.test(sym) ? `${sym.toUpperCase()}-${addrPrefix(b.address)}` : addrPrefix(b.address)
}

/** The short path for a basket. This is what the app mints from now on. */
export function basketHref(b: { symbol: string; address: string; chainId: number }): string {
  return `/t/${chainSlug(b.chainId)}/${basketRef(b)}`
}

/** The long form, still generated by nothing but kept exact for the resolver
 *  and for anything that needs to reason about the legacy shape. */
export function basketHrefLong(b: { address: string; chainId: number }): string {
  return `/token?addr=${b.address}&chain=${b.chainId}`
}

export interface RefMatch {
  /** Exactly one basket matched — resolve straight to it. */
  hit: BasketSummary | null
  /** More than one matched a BARE symbol: the caller must disambiguate rather
   *  than pick, because picking would send someone to the wrong basket. */
  ambiguous: BasketSummary[]
}

/**
 * Resolve a short ref against the discovered basket list.
 *
 * Accepts, in order of confidence:
 *   · a full 0x address                  — always exact
 *   · `SYMBOL-<hexprefix>` or a bare hex prefix — exact via the address half
 *   · a bare SYMBOL                      — exact only when one basket matches
 *
 * `chainId` narrows the search when the path carried one. A ref that matches
 * nothing returns both fields empty, which the page renders as not-found —
 * never as a silent redirect somewhere plausible.
 */
export function resolveBasketRef(ref: string, chainId: number | null, all: BasketSummary[]): RefMatch {
  const none: RefMatch = { hit: null, ambiguous: [] }
  const raw = (ref ?? '').trim()
  if (!raw) return none
  const pool = chainId == null ? all : all.filter((b) => b.chainId === chainId)

  // full address — case-insensitive on the 0x too, since a pasted address may
  // arrive checksummed or shouted
  if (/^0x[0-9a-f]{40}$/i.test(raw)) {
    return { hit: pool.find((b) => b.address.toLowerCase() === raw.toLowerCase()) ?? null, ambiguous: [] }
  }

  const dash = raw.lastIndexOf('-')

  // EXACT SYMBOL FIRST, before the hex branch. A ticker that merely looks
  // hexadecimal — FACADE, C0FFEE, DECADE, BADA55, CAFEBABE — otherwise gets
  // read as an address prefix, and basket addresses are CREATE2 with a salt the
  // launch flow already brute-forces, so mining `0xfacade…` to hijack the bare
  // ticker FACADE is a routine vanity-address job rather than a coincidence.
  const whole = pool.filter((b) => b.symbol.toUpperCase() === raw.toUpperCase())
  if (whole.length === 1) return { hit: whole[0], ambiguous: [] }
  if (whole.length > 1) return { hit: null, ambiguous: whole }

  // SYMBOL-<hex>, or a bare hex prefix.
  const tail = dash >= 0 ? raw.slice(dash + 1) : raw
  if (/^[0-9a-fA-F]{6,40}$/.test(tail)) {
    const t = tail.toLowerCase()
    const byPrefix = pool.filter((b) => b.address.toLowerCase().slice(2).startsWith(t))
    // THE SYMBOL HALF IS CHECKED, not decoration. Skipping it made the human
    // half a free-text field anyone could fill in: `/t/b/USDC-<their own 8
    // hex>` resolved straight to their basket and rendered a buy console, at
    // zero cost — no grinding, no collision. A ref whose two halves disagree is
    // refused outright rather than quietly trusting the address.
    const named = dash >= 0 ? raw.slice(0, dash).toUpperCase() : null
    const agree = named == null ? byPrefix : byPrefix.filter((b) => b.symbol.toUpperCase() === named)
    if (named != null && byPrefix.length > 0 && agree.length === 0) return none
    if (agree.length === 1) return { hit: agree[0], ambiguous: [] }
    if (agree.length > 1) return { hit: null, ambiguous: agree }
  }

  // bare symbol from a dashed ref (e.g. a symbol that itself contains a dash
  // was minted as prefix-only, but someone typed the ticker)
  const sym = (dash >= 0 ? raw.slice(0, dash) : raw).toUpperCase()
  const bySymbol = pool.filter((b) => b.symbol.toUpperCase() === sym)
  if (bySymbol.length === 1) return { hit: bySymbol[0], ambiguous: [] }
  if (bySymbol.length > 1) return { hit: null, ambiguous: bySymbol }
  return none
}

// ── creators ─────────────────────────────────────────────────────────────────

/** The short path for a creator.
 *
 *  Deliberately ADDRESS-ONLY. An ENS name would be shorter and far more
 *  legible — `/c/colby.eth` — but the creator page resolves an address and
 *  nothing on it resolves a name, so minting a name here would produce links
 *  that 404. Adding it means teaching that page forward-ENS resolution first;
 *  until then this stays a trap nobody can fall into. */
export function creatorHref(address: string): string {
  return `/c/${address.toLowerCase()}`
}

// ── bundles ──────────────────────────────────────────────────────────────────

/** The short path for a published bundle. The slug is already short, so this
 *  only trims the route prefix. Address-only for the same reason as above. */
export function bundleHref(creator: string, slug: string): string {
  return `/b/${creator.toLowerCase()}/${slug}`
}
