// Generate the Chrome Web Store submission pack, branded from the operator's
// own config — everything the dashboard asks for on first publish:
//
//   store/listing.md         paste-ready listing text: name, 132-char summary,
//                            description, category, single-purpose statement,
//                            per-permission justifications, privacy answers
//   store/screenshot-*.png   1280×800 store screenshots rendered from the
//                            operator's OWN branded popup (needs the playwright
//                            headless shell, same dev-tool class as make-icons;
//                            skipped gracefully when absent)
//
// Usage: node scripts/store-assets.mjs   (dev server must NOT be running on
// 5199 — the script starts its own)

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { execFileSync, spawn } from 'node:child_process'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, '..')
const out = resolve(root, 'store')
mkdirSync(out, { recursive: true })

// Brand: read the built manifest when present (authoritative), else fall back
// to parsing brand.config for the name.
let name = 'Spectrum · Portfolio Lens'
let version = '0.1.0'
try {
  const m = JSON.parse(readFileSync(resolve(root, 'dist/manifest.json'), 'utf8'))
  name = m.name
  version = m.version
} catch {
  /* build not run yet — defaults above */
}
const brandName = name.split('·')[0].trim()

// ── 1 · listing.md ───────────────────────────────────────────────────────────

const SUMMARY = `Read-only portfolio lens: your ${brandName} baskets across chains, drift against your targets, honest local alerts.`

const listing = `# Chrome Web Store listing · ${name} v${version}

> Generated by scripts/store-assets.mjs. Paste-ready. Recommended visibility
> for white-label operator builds: **Unlisted** (anyone with the link installs
> one-click from your /extension page; no store-search presence).

## Name
${name}

## Summary (≤132 chars)
${SUMMARY}

## Category
Tools (alternatively: Productivity)

## Description
A read-only lens over the basket portfolio you already hold. It never
connects to your wallet, never signs, never asks for a seed phrase. You
paste an address to watch, and every action hands off to your own
${brandName} site, which recomputes from live chain state.

WHAT IT SHOWS
• Net per-asset exposure: your held baskets decomposed into one line per
  underlying asset, across every supported chain.
• Target weights and drift: set the mix you chose; each line shows how far
  you've drifted from it, in points, with the target marked on the bar.
• Which baskets drive each line: every exposure row opens into its
  per-basket breakdown.
• Baskets you created, with live AUM and 24h movement.

HONEST ALERTS, LOCALLY
Alert rules run in your browser on a cadence you pick (checked every N
minutes while your browser is open, never "real-time", because that would
be a lie). Drift beyond your threshold, portfolio value crossings, and 24h
moves on held baskets. Every alert states a fact about your own position;
nothing here gives advice. Rules and settings live in your own browser
storage. No account, no server, no analytics, no telemetry.

WHAT IT CANNOT DO, BY DESIGN
It holds no keys and cannot sign or move money. It reads public chain data
through the same endpoints the site uses, and nothing else.

We will never ask for a seed phrase or a signature in this extension. The
only official download source is the extension page on your ${brandName}
site.

## Single-purpose statement
This extension has one purpose: passively displaying the on-chain portfolio
of a user-specified public address and notifying the user of changes they
asked to be told about. It performs no transactions, injects nothing into
web pages beyond a presence marker on the operator's own site, and collects
no user data.

## Permission justifications
- alarms: schedules the periodic read-only portfolio check the user
  configures (floor: every 5 minutes).
- storage: stores the user's own settings (watched address, targets, alert
  rules) and the cached last read, locally and in their browser sync.
- notifications: shows the alerts the user's own rules produce; nothing
  else triggers a notification.
- host permissions (RPC + price endpoints): read-only chain and price
  queries; these are the same public endpoints the operator's website reads.
- content script on the operator's own origin only: stamps a presence
  marker so the site can offer this extension only to visitors who don't
  have it. It reads nothing from the page.

## Privacy tab answers
- Does it collect user data? No. The watched address and settings stay in
  the user's browser (chrome.storage). Nothing is transmitted to the
  developer. Chain reads go directly from the user's browser to public RPC
  endpoints.
- Privacy policy URL: use your site's /privacy page.

## Assets checklist
- [x] Icon 128×128: ships in the zip (icons/icon-128.png)
- [ ] Screenshots 1280×800: store/screenshot-*.png (this script)
- [ ] Small promo tile 440×280: optional; crop screenshot-1 if wanted
`

writeFileSync(resolve(out, 'listing.md'), listing)
console.log('store/listing.md written')

// ── 2 · screenshots ──────────────────────────────────────────────────────────
// Rendered from the operator's own branded popup via the store-shot frame.

const SHOTS = [
  ['full', 'Your whole portfolio. One lens.', 'screenshot-1.png'],
  ['drill', 'See which baskets drive every asset.', 'screenshot-2.png'],
  ['empty', 'Read-only. Never connects, never signs.', 'screenshot-3.png'],
]

// A local Chromium for playwright-core: explicit env wins, else the
// ms-playwright cache (either the headless shell or the full build).
function findChromium() {
  if (process.env.PLAYWRIGHT_CHROMIUM_PATH) return process.env.PLAYWRIGHT_CHROMIUM_PATH
  try {
    const cache = join(homedir(), 'Library/Caches/ms-playwright')
    for (const dir of readdirSync(cache).sort().reverse()) {
      for (const rel of ['chrome-mac/headless_shell', 'chrome-mac/Chromium.app/Contents/MacOS/Chromium']) {
        const p = join(cache, dir, rel)
        if ((dir.startsWith('chromium') || dir.startsWith('chromium_headless_shell')) && existsSync(p)) return p
      }
    }
  } catch {
    /* no cache */
  }
  return null
}

const server = spawn('npx', ['vite', 'dev', '--port', '5199', '--strictPort'], {
  cwd: root,
  stdio: 'ignore',
  detached: false,
})
try {
  await new Promise((r) => setTimeout(r, 3500))
  const executablePath = findChromium()
  if (!executablePath) throw new Error('no chromium')
  const { chromium } = await import('playwright-core')
  const browser = await chromium.launch({ executablePath })
  const page = await browser.newPage({ viewport: { width: 1280, height: 800 } })
  for (const [state, caption, file] of SHOTS) {
    const s = state === 'drill' ? 'full' : state
    await page.goto(
      `http://localhost:5199/src/popup/store-shot.html?state=${s}&caption=${encodeURIComponent(caption)}`,
    )
    await page.waitForTimeout(6000)
    if (state === 'drill') {
      // The real thing: open the top exposure row's contribution drill
      // inside the framed popup before shooting.
      await page
        .frameLocator('#frame')
        .getByRole('button', { name: /WETH/ })
        .click()
        .catch(() => undefined) // preview fixtures changed? ship the resting state
      await page.waitForTimeout(700)
    }
    await page.screenshot({ path: resolve(out, file) })
    console.log(`store/${file} — “${caption}”`)
  }
  await browser.close()
} catch {
  console.log(
    'screenshots skipped (no local Chromium for playwright-core — set PLAYWRIGHT_CHROMIUM_PATH or run: npx playwright@1.49.1 install chromium)',
  )
} finally {
  server.kill()
}
