import type { BrandConfig } from './brand'
import { PAGE_KEYS } from './brand'

// Serialize a draft BrandConfig to the exact brand.config.ts text the setup studio hands
// the operator to commit (mirrors what the create/ wizard writes). Only OFF pages are
// emitted (default-on), matching the runtime contract.
export function brandConfigToTs(brand: BrandConfig): string {
  const p = brand.palette
  const q = (s: string) => JSON.stringify(s)
  const off = PAGE_KEYS.filter((k) => brand.pages?.[k] === false)

  const L: string[] = [`import type { BrandConfig } from './theme/brand'`, '']
  L.push('// Generated by the on-site Setup studio. Commit this file to lock your look in.')
  L.push('export const brand: BrandConfig = {')
  L.push(`  name: ${q(brand.name)},`)
  if (brand.tagline) L.push(`  tagline: ${q(brand.tagline)},`)
  L.push(`  style: ${q(brand.style)},`)
  L.push('  palette: {')
  L.push(`    gradientFrom: ${q(p.gradientFrom)},`)
  L.push(`    gradientVia: ${q(p.gradientVia)},`)
  L.push(`    gradientTo: ${q(p.gradientTo)},`)
  if (p.accent) L.push(`    accent: ${q(p.accent)},`)
  L.push('  },')
  if (off.length) {
    L.push('  pages: {')
    for (const k of off) L.push(`    ${k}: false,`)
    L.push('  },')
  }
  // default-on knobs: emitted only when the operator turned them OFF / set them
  if (brand.stocks === false) L.push('  stocks: false,')
  if (brand.prismCredit === false) L.push('  prismCredit: false,')
  if (brand.starterTokens === false) L.push('  starterTokens: false,')
  // setupStudio must round-trip too: without it, an operator who LOCKED their
  // site with --no-setup-studio and then pressed Apply on a dev build silently
  // got /setup + the footer Customize link back on their next production build.
  if (brand.setupStudio === false) L.push('  setupStudio: false,')
  if (brand.defaultChainId != null) L.push(`  defaultChainId: ${brand.defaultChainId},`)
  L.push('}', '', 'export default brand', '')
  return L.join('\n')
}
