#!/usr/bin/env node
// Build the MCP server: bundle mcp/server.ts WITH the app's own money modules
// (reuse, never recreation) into one node-runnable file. esbuild comes from
// the app's node_modules (vite ships it) — no new dependency anywhere.
//
// The app source is written for Vite, so `import.meta.env.*` appears at
// module scope; esbuild's `define` maps each occurrence to the process.env
// equivalent so the SAME code runs node-side with the operator's env. The
// key list is the measured inventory (the product-split spike's NEXT-SEAMS
// catalogue) — regenerate with:
//   grep -rhoE 'import\.meta\.env\.[A-Z0-9_]*' app/src | sort -u
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

// esbuild lives in the app's node_modules (vite ships it), so a FRESH CLONE has
// not got it yet. Say that in one sentence instead of throwing a raw
// ERR_MODULE_NOT_FOUND stack at someone on their first minute with the kit —
// which is exactly what the v2026.08.21 install test walked into.
const ESBUILD = join(dirname(fileURLToPath(import.meta.url)), '..', 'app', 'node_modules', 'esbuild', 'lib', 'main.js')
if (!existsSync(ESBUILD)) {
  console.error(
    'mcp build: the app\'s dependencies are not installed yet, and the bundler comes from there.\n' +
      '           Run this first:  cd app && npm install\n' +
      '           Then:            npm run mcp:build',
  )
  process.exit(1)
}
const { build } = await import(ESBUILD)

const HERE = dirname(fileURLToPath(import.meta.url))

// Build provenance, stamped into the bundle (spectrum_health reports both):
// the kit version from the repo root's version.json — the kit's own release
// identity, not a separate MCP number — and the moment this bundle was built.
const KIT_VERSION = String(JSON.parse(readFileSync(join(HERE, '../version.json'), 'utf8')).version ?? 'unknown')
const BUILD_STAMP = new Date().toISOString()

const VITE_KEYS = ['AERODROME_FACTORY_ADDRESS', 'AGENT_ENDPOINT', 'ALCHEMY_API_KEY', 'BASE_RPC_URL', 'DEFAULT_CHAIN_ID', 'DEV_FIXTURE', 'DIRECT_SWAP_WRAPPER_ADDRESS', 'ENABLE_DEPLOY', 'ENABLE_RANGE_ORDERS', 'ENABLE_SWAP', 'ENABLE_TRADING', 'ENABLE_WALLET', 'EXTRA_CHAIN_IDS', 'FACTORY_ADDRESS', 'HIDDEN_BASKETS', 'LEAGUE_POOL_ADDRESS', 'MAINNET_RPC_URL', 'MIGRATE_REBALANCE', 'NOTES_REGISTRY_ADDRESS', 'POOL_MANAGER_ADDRESS', 'ROBINHOOD_RPC_URL', 'SNAPSHOT_MAX_AGE_SEC', 'SNAPSHOT_URL', 'SWAP_ROUTER_ADDRESS', 'UNIV2_FACTORY_ADDRESS', 'UNIV3_FACTORY_ADDRESS', 'UNIV3_QUOTER_ADDRESS', 'UNIV3_SWAP_ROUTER_ADDRESS', 'UNIVERSAL_ROUTER_ADDRESS', 'USDC_ADDRESS', 'V4_QUOTER_ADDRESS', 'VERIFY_BASKET', 'VERIFY_BATCHER', 'WALLETCONNECT_PROJECT_ID', 'WETH_ADDRESS']

const define = { 'import.meta.glob': 'globalThis.__viteGlob', 'import.meta.env': 'globalThis.__viteEnv', 'import.meta.env.DEV': 'false', 'import.meta.env.PROD': 'true', 'import.meta.env.MODE': '"production"' }
for (const k of VITE_KEYS) define[`import.meta.env.VITE_${k}`] = `process.env.VITE_${k}`
define['__KIT_VERSION__'] = JSON.stringify(KIT_VERSION)
define['__BUILD_STAMP__'] = JSON.stringify(BUILD_STAMP)

await build({
  entryPoints: [join(HERE, 'server.ts')],
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  outfile: join(HERE, 'dist/server.mjs'),
  define,
  // the app imports a YAML banlist via Vite's `?raw` (tags.ts, reached through
  // resolveAsset); esbuild has no Vite loaders, so map both the query form and
  // the extension to `text` — the string arrives identical to what Vite ships
  loader: { '.yml': 'text' },
  inject: [join(HERE, 'prelude.mjs')],
  // fully self-contained: viem bundles in too (a dist that needs a sibling
  // node_modules is a trap for every operator who copies it). nodePaths lets
  // THIS file's imports resolve from the app's modules — server.ts lives in
  // mcp/, outside the app tree, and esbuild resolves per importing file.
  nodePaths: [join(HERE, '../app/node_modules')],
  logLevel: 'warning',
})
console.log('mcp: built dist/server.mjs')

// ── the tools manifest (drift-killer): GENERATED from the built registry so
// the /mcp page, the docs, and the server can never disagree about what
// exists. Imported with the wire off; alphabetical so rebuilds do not churn
// the committed diff. Kind is derived from the name — the same taxonomy the
// docs speak (read / quote / compose / execute).
process.env.MCP_NO_WIRE = '1'
const { TOOLS, PROMPTS } = await import(join(HERE, 'dist/server.mjs'))
const kindOf = (name) =>
  name === 'spectrum_execute' ? 'execute' : name.startsWith('spectrum_quote_') ? 'quote' : name.startsWith('spectrum_compose_') ? 'compose' : 'read'
const manifest = {
  $comment: 'GENERATED by mcp/build.mjs from the server registry — edit the server, never this file.',
  version: KIT_VERSION,
  tools: Object.entries(TOOLS)
    .map(([name, t]) => ({ name, kind: kindOf(name), description: String(t.description).split('. ')[0] + '.' }))
    .sort((a, b) => a.name.localeCompare(b.name)),
  prompts: Object.entries(PROMPTS)
    .map(([name, p]) => ({ name, description: p.description }))
    .sort((a, b) => a.name.localeCompare(b.name)),
}
writeFileSync(join(HERE, 'tools.json'), JSON.stringify(manifest, null, 2) + '\n')
// the app-side twin: the /mcp page maps this file, so the site's tool table
// and the server registry are the same generated artifact and cannot drift
writeFileSync(join(HERE, '../app/src/generated/mcp-tools.json'), JSON.stringify(manifest, null, 2) + '\n')
console.log(`mcp: tools.json regenerated (${manifest.tools.length} tools, ${manifest.prompts.length} prompts) + app/src/generated twin`)
