// Pure config renderers for the Spectrum Mini onboarding wizard. Kept dependency-free
// and separate from the CLI so they're unit-testable (node --test). They emit the two
// files the operator app reads: app/src/brand.config.ts + app/.env.local.

export const STYLES = ['spectral', 'aurora', 'prism', 'umbra', 'sylvan']
export const MAX_SITE_NAME = 32
// Toggleable pages (default-on); mirrors PageToggles in src/theme/brand.ts.
export const PAGE_KEYS = [
  'discover', 'launch', 'trade', 'fees', 'portfolio', 'creators', 'refer', 'integrate', 'docs',
]
export const SPECTRUM_DNA = { from: '#ff9248', via: '#ff4db8', to: '#35e0ff' }

// Named gradient presets (mirror app/src/theme/catalog.ts) — pick one with --gradient <id>.
export const GRADIENT_CATALOG = [
  { id: 'spectrum', from: '#ff9248', via: '#ff4db8', to: '#35e0ff' },
  { id: 'ocean', from: '#3b82f6', via: '#06b6d4', to: '#22d3ee' },
  { id: 'ember', from: '#f59e0b', via: '#ef4444', to: '#ec4899' },
  { id: 'borealis', from: '#22d3ee', via: '#34d399', to: '#a855f7' },
  { id: 'sunset', from: '#f97316', via: '#f43f5e', to: '#a855f7' },
  { id: 'mint', from: '#34d399', via: '#10b981', to: '#06b6d4' },
  { id: 'grape', from: '#8b5cf6', via: '#a855f7', to: '#d946ef' },
  { id: 'gold', from: '#fbbf24', via: '#f59e0b', to: '#f97316' },
  { id: 'rose', from: '#fb7185', via: '#f43f5e', to: '#e11d48' },
  { id: 'ice', from: '#93c5fd', via: '#67e8f9', to: '#a5f3fc' },
  { id: 'magma', from: '#ef4444', via: '#f97316', to: '#fbbf24' },
  { id: 'monochrome', from: '#d1d5db', via: '#9ca3af', to: '#6b7280' },
  { id: 'ultraviolet', from: '#6366f1', via: '#8b5cf6', to: '#d946ef' },
  { id: 'citrus', from: '#a3e635', via: '#facc15', to: '#fb923c' },
]

export function resolveGradient(id) {
  const g = GRADIENT_CATALOG.find((x) => x.id === id)
  return g ? { from: g.from, via: g.via, to: g.to } : null
}

// Name guard — mirrors validateSiteName in src/theme/brand.ts (no operator is "Spectrum").
export function validateSiteName(name) {
  const n = (name || '').trim()
  if (!n) return { ok: false, error: 'Site name is required' }
  if (n.length > MAX_SITE_NAME) return { ok: false, error: `Site name must be ${MAX_SITE_NAME} characters or fewer` }
  if (/spectrum/i.test(n)) return { ok: false, error: 'Site name may not contain "Spectrum"' }
  return { ok: true }
}

function tsObject(obj, indent) {
  const pad = ' '.repeat(indent)
  const inner = Object.entries(obj)
    .map(([k, v]) => `${pad}  ${k}: ${typeof v === 'string' ? JSON.stringify(v) : v},`)
    .join('\n')
  return `{\n${inner}\n${pad}}`
}

/** Render app/src/brand.config.ts from a plan. Only emits pages that are OFF (default-on). */
export function renderBrandConfig(plan) {
  const p = plan.palette || {}
  const palette = { gradientFrom: p.from || SPECTRUM_DNA.from, gradientVia: p.via || SPECTRUM_DNA.via, gradientTo: p.to || SPECTRUM_DNA.to }
  if (p.accent) palette.accent = p.accent
  const off = {}
  for (const k of plan.pagesOff || []) if (PAGE_KEYS.includes(k)) off[k] = false

  const L = [`import type { BrandConfig } from './theme/brand'`, '']
  L.push('// Generated by create-spectrum-mini. Edit freely; the wizard can also rewrite it.')
  L.push('// name is a text wordmark (no logo) and must not contain "Spectrum".')
  L.push('export const brand: BrandConfig = {')
  L.push(`  name: ${JSON.stringify(plan.name)},`)
  if (plan.tagline) L.push(`  tagline: ${JSON.stringify(plan.tagline)},`)
  L.push(`  style: ${JSON.stringify(STYLES.includes(plan.style) ? plan.style : 'spectral')},`)
  L.push(`  palette: ${tsObject(palette, 2)},`)
  if (Object.keys(off).length) L.push(`  pages: ${tsObject(off, 2)}, // omitted keys stay ON`)
  L.push('}', '', 'export default brand', '')
  return L.join('\n')
}

// Every tier connects a wallet; the tier sets what a connected visitor can DO. The default
// is ALL of it (every deployment ships the full functionality); narrower tiers scope down.
const TIER_FLAGS = {
  all: { wallet: true, deploy: true, trading: true, swap: true },
  info: { wallet: true },
  creation: { wallet: true, deploy: true },
  fees: { wallet: true, trading: true },
  marketplace: { wallet: true, swap: true },
}

/** The committed deploy identity: app/src/site.config.json (site URL + fee wallet; both
 *  ship in the public bundle anyway). The RPC key stays OUT — gitignored .env.local only. */
export function renderSiteConfig(plan) {
  const f = TIER_FLAGS[plan.tier] ?? TIER_FLAGS.all
  return JSON.stringify({
    siteUrl: (plan.siteUrl || '').trim(),
    feeWallet: (plan.feeWallet || '').trim(),
    features: { wallet: !!f.wallet, deploy: !!f.deploy, trading: !!f.trading, swap: !!f.swap },
  }, null, 2) + '\n'
}

/** Render app/.env.local from a plan. No fabricated addresses; DB omitted by design. */
export function renderEnv(plan) {
  const L = ['# Generated by create-spectrum-mini. Vite reads .env.local (not .env.example).', '']
  L.push('# Your tier (feature flags), site URL and fee wallet live in the COMMITTED')
  L.push('# src/site.config.json — this file carries ONLY the value kept out of git.', '')
  if (plan.factory) {
    L.push('# Factory override — points the site at your OWN deployment (blank/absent = canonical).')
    L.push(`VITE_FACTORY_ADDRESS=${plan.factory}`, '')
  }

  if (plan.swapRouter) {
    L.push('# Swap router override — routes buy/sell through your OWN router (blank/absent = canonical).')
    L.push(`VITE_SWAP_ROUTER_ADDRESS=${plan.swapRouter}`, '')
  }
  L.push('# RPC key (required before deploy) — ships in the public bundle; use a domain-restricted key.')
  L.push('# The ONE value kept out of git: on a git-connected CI build, set VITE_ALCHEMY_API_KEY')
  L.push('# in the host dashboard/CLI.')
  L.push(`VITE_ALCHEMY_API_KEY=${plan.rpcKey || ''}`, '')
  L.push('# Your site URL + fee wallet live in the COMMITTED src/site.config.json (written by')
  L.push('# this wizard); the VITE_* vars in .env.example remain as overrides.', '')
  if (plan.walletConnectId) {
    L.push('# WalletConnect project id — adds mobile / QR wallets (injected wallets work without it).')
    L.push(`VITE_WALLETCONNECT_PROJECT_ID=${plan.walletConnectId}`, '')
  }
  L.push('# Contracts are the shipped canonical Spectrum deployment (Base, Ethereum + Robinhood Chain).')
  L.push('# Serving your OWN deployment instead is a hand-edit power path — every override')
  L.push('# (factory, swap router, public infra) is documented in .env.example.')
  L.push('# Database intentionally omitted — the Spectrum Mini kit ships DB-less. Discovery,')
  L.push('# charts, leaderboards, launch, and referrals all run on chain data alone.')
  L.push('# Creator thesis/profile is deployer-signed JSON. To show it to ALL visitors with no')
  L.push('# backend, commit each signed blob to app/metadata/<chainId>/<basket>.json (ships in the')
  L.push('# build). VITE_METADATA_BASE_URL is an optional external host for baskets you do not bundle;')
  L.push('# never add VITE_SUPABASE_URL (there is no database).')
  return L.join('\n') + '\n'
}

// ── hosting guidance (owner 2026-07-10: the wizard walks the chosen host) ──────
// Pure: returns printable lines for the host the operator picked, so the terminal
// flow ends with THEIR next steps, not a generic pointer. Unknown → 'later'.
export const HOSTS = ['zip', 'cloudflare', 'netlify', 'vercel', 'vps', 'later']

export function hostingGuide(host) {
  const h = HOSTS.includes(host) ? host : 'later'
  const build = 'cd app && npm run check:config && npm run verify:chain'
  const G = {
    zip: [
      'Hosting — drag and drop (no accounts CLI, easiest):',
      `  1. ${build}`,
      '  2. npm run package            # builds + emits app/<name>-site.zip',
      '  3. Open https://app.netlify.com/drop in a browser and drag the zip onto it',
      '     (Cloudflare Pages → "Upload assets" takes the same zip). Live in ~30s.',
      '  4. If the host gives you a different URL than your configured site URL,',
      '     update it (re-run this wizard or edit src/site.config.json), rebuild, re-drop.',
    ],
    cloudflare: [
      'Hosting — Cloudflare Pages (CLI):',
      `  1. ${build} && npm run build`,
      '  2. npx wrangler login          # one browser click',
      '  3. npx wrangler pages project create <name>',
      '  4. npx wrangler pages deploy dist --project-name <name>   # live <name>.pages.dev',
      '  Redeploy after changes with the same deploy command. Deep links ship working',
      '  (dist/_redirects). Custom domain: npx wrangler pages domain add, or the dashboard.',
    ],
    netlify: [
      'Hosting — Netlify (CLI):',
      `  1. ${build}`,
      '  2. npx netlify login           # one browser click',
      '  3. npx netlify init            # create the site',
      '  4. npx netlify deploy --build --prod',
      '  The repo-root netlify.toml drives base/build and deploys the per-URL OG-card',
      '  edge function automatically. Prefer no CLI? npm run package + https://app.netlify.com/drop.',
    ],
    vercel: [
      'Hosting — Vercel (CLI):',
      `  1. ${build} && npm run build`,
      '  2. npx vercel login            # one browser click',
      '  3. npx vercel --prod           # from app/ (framework: Vite; vercel.json ships)',
      '  Note: Vercel’s free tier is non-commercial per its ToS.',
    ],
    vps: [
      'Hosting — your own server (VPS: nginx / Apache / Caddy):',
      `  1. ${build}`,
      '  2. npm run package             # or npm run build and use the dist/ folder',
      '  3. Upload the CONTENTS of app/dist/ to your web root, e.g.:',
      '       rsync -av --delete app/dist/ user@your-server:/var/www/your-site/',
      '     (or scp/SFTP the zip there and unzip it).',
      '  4. Add TWO server rules — the SPA catch-all + the nested-route asset remap',
      '     (without it, refreshing /creator/… serves index.html AS the script → blank page).',
      '     nginx, inside your server block:',
      '       location ~ ^/.+/(assets/.+)$ { try_files /$1 =404; }',
      '       location / { try_files $uri $uri/ /index.html; }',
      '  5. Serve over HTTPS (wallets require a secure context) — certbot/Caddy handle this.',
      '  New to servers? Caddy is the easy path: automatic HTTPS, ~10-line config.',
      '  Complete paste-ready configs (nginx/Apache/Caddy incl. cache headers so',
      '  redeploys never go stale) + a curl self-check: app/SETUP.md → "Your own server".',
    ],
    later: [
      'Hosting — decide later:',
      `  When ready: ${build} && npm run package  → drag the zip onto a drop host,`,
      '  or the CLI/VPS paths in app/SETUP.md → "5 · Deploy" (nginx/Apache/Caddy included).',
    ],
  }
  return G[h]
}

export { TIER_FLAGS }
