#!/usr/bin/env node
// Generate public/sitemap.xml from the site URL + the public content routes. Runs in the
// prebuild hook (after check-config). No origin set → WRITES the origin-less stub (a sitemap
// needs ABSOLUTE urls, and the kit ships no origin — never points at anyone else's property).
// Always writing is the point (kit audit): the file is build OUTPUT, gitignored — the old
// exit-without-writing left a PREVIOUS build's origin sitting in the file, so clearing the
// site URL still shipped the stale origin while this script claimed it "left the stub".
import { readFileSync, existsSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const APP_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..')

// Read a VITE_ var the way Vite resolves it: a real shell var wins, else .env.local.
function envValue(key) {
  if (process.env[key]) return process.env[key]
  const p = resolve(APP_DIR, '.env.local')
  if (!existsSync(p)) return ''
  for (const raw of readFileSync(p, 'utf8').split('\n')) {
    const line = raw.trim()
    if (!line || line.startsWith('#')) continue
    const eq = line.indexOf('=')
    if (eq === -1 || line.slice(0, eq).trim() !== key) continue
    let v = line.slice(eq + 1).trim()
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1)
    return v
  }
  return ''
}

// Public, crawlable content routes (dynamic token/creator pages + wallet/flag-gated
// transactional pages excluded). Each carries the brand.pages key that gates it, so a
// page the operator switched OFF is never advertised to crawlers as a 404 — the list
// used to be hardcoded and had drifted six routes behind the app (kit audit).
const ALL_ROUTES = [
  { path: '/', page: null },
  { path: '/explore', page: 'discover' },
  { path: '/launch', page: 'launch' },
  { path: '/creators', page: 'creators' },
  { path: '/earn', page: 'refer' },
  { path: '/league', page: 'league' },
  { path: '/bundle', page: 'bundle' },
  { path: '/claim', page: 'claim' },
  { path: '/integrate', page: 'integrate' },
  // /faq is a REDIRECT to /learn now — listing it would advertise a soft-404 to
  // crawlers and split one page's ranking across two URLs.
  { path: '/learn', page: 'docs' },
  { path: '/docs', page: 'docs' },
  { path: '/verify', page: null },
  { path: '/terms', page: null },
  { path: '/privacy', page: null },
  { path: '/risk', page: null },
]

/** Page keys the operator turned OFF in brand.config.ts. The generated file only ever
 *  emits `key: false` inside a `pages: { … }` block, and a hand-edited one keeps that
 *  shape. On any parse trouble we return an empty set: listing a disabled page is a
 *  small SEO wart, but DROPPING a live page from the sitemap is the worse failure. */
function disabledPages() {
  try {
    const src = readFileSync(resolve(APP_DIR, 'src/brand.config.ts'), 'utf8')
    const block = /pages:\s*\{([\s\S]*?)\}/.exec(src)
    if (!block) return new Set()
    return new Set([...block[1].matchAll(/(\w+)\s*:\s*false/g)].map((m) => m[1]))
  } catch {
    return new Set()
  }
}

const off = disabledPages()
const ROUTES = ALL_ROUTES.filter((r) => !r.page || !off.has(r.page)).map((r) => r.path)
function siteConfigValue(key) {
  try {
    return String(JSON.parse(readFileSync(resolve(APP_DIR, 'src/site.config.json'), 'utf8'))[key] ?? '')
  } catch {
    return ''
  }
}
const origin = (envValue('VITE_SITE_URL') || siteConfigValue('siteUrl')).trim().replace(/\/$/, '')
const out = resolve(APP_DIR, 'public/sitemap.xml')

if (!origin) {
  const stub = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Origin-less stub, regenerated by every build. Set your site URL
     (src/site.config.json siteUrl, or VITE_SITE_URL) and rebuild to emit the
     real sitemap — it needs absolute URLs, and this package ships no origin;
     it must never point at any property of this package's authors. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
</urlset>
`
  writeFileSync(out, stub)
  console.log('sitemap: no site URL (src/site.config.json siteUrl / VITE_SITE_URL) — wrote the origin-less stub.')
  process.exit(0)
}

const urls = ROUTES.map((r) => `  <url><loc>${origin}${r}</loc></url>`).join('\n')
const xml = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`
writeFileSync(out, xml)
console.log(`sitemap: wrote ${ROUTES.length} routes for ${origin}`)
