#!/usr/bin/env node
/**
 * Writes the security headers into BOTH deployment surfaces from ONE source
 * (scripts/csp.mjs), because this app ships to Netlify (`public/_headers`) and
 * Vercel (`vercel.json`) and a policy that exists on one host and not the other
 * is a policy an operator cannot rely on.
 *
 * Runs in `prebuild`, so the headers cannot drift from the allowlist: editing
 * the origin list is the only way to change them, and forgetting to re-run it
 * is not possible.
 *
 * ⚠ IT PRESERVES WHAT IS ALREADY THERE. The extension's xpinstall MIME rule is
 * load-bearing for Firefox one-click install; this rewrites only the block it
 * owns, marked by the fences below.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { EMBED_HEADER_OVERRIDES, SECURITY_HEADERS } from './csp.mjs'

const APP = join(dirname(fileURLToPath(import.meta.url)), '..')
const BEGIN = '# BEGIN security headers (generated by scripts/emit-headers.mjs — edit scripts/csp.mjs)'
const END = '# END security headers'

// ── Netlify ─────────────────────────────────────────────────────────────────
const headersPath = join(APP, 'public/_headers')
const existing = readFileSync(headersPath, 'utf8')
const block = [
  BEGIN,
  '/*',
  ...Object.entries(SECURITY_HEADERS).map(([k, v]) => `  ${k}: ${v}`),
  END,
].join('\n')
const withoutOld = existing.includes(BEGIN)
  ? existing.slice(0, existing.indexOf(BEGIN)) + existing.slice(existing.indexOf(END) + END.length)
  : existing
writeFileSync(headersPath, `${block}\n\n${withoutOld.trim()}\n`)

// ── Vercel ──────────────────────────────────────────────────────────────────
const vercelPath = join(APP, 'vercel.json')
const vercel = JSON.parse(readFileSync(vercelPath, 'utf8'))
const generated = {
  source: '/(.*)',
  headers: Object.entries(SECURITY_HEADERS).map(([key, value]) => ({ key, value })),
}
// the /embed exception — LAST, because Vercel resolves duplicate header keys
// by the last matching rule (the Netlify half is the embed-headers edge
// function; _headers cannot loosen). X-Frame-Options: null means REMOVE — on
// Vercel that is expressed by simply not stating it, plus the CSP override.
const embed = {
  source: '/embed',
  headers: Object.entries({ ...SECURITY_HEADERS, ...EMBED_HEADER_OVERRIDES })
    .filter(([, value]) => value !== null)
    .map(([key, value]) => ({ key, value })),
}
// keep every hand-written rule, replace only ours (identified by source)
vercel.headers = [generated, embed, ...(vercel.headers ?? []).filter((h) => h.source !== '/(.*)' && h.source !== '/embed')]
writeFileSync(vercelPath, `${JSON.stringify(vercel, null, 2)}\n`)

console.log(`security headers written: ${Object.keys(SECURITY_HEADERS).length} to public/_headers and vercel.json`)
